name: neomarket_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mysql_client: ^0.0.25
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.0
  bcrypt: ^1.0.0
  ftpconnect: ^2.0.0
  logger: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icono.png
